language: groovy
jdk:
  - oraclejdk7
env:
  GRAILS_VERSION=2.4.4
  GRAILS_VERSION=2.3.0
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true
branches:
  only:
    - master
script: grails clean
  && [[ GRAILS_VERSION =~ ([1-2]\.[0-3]\.[0-9]) ]] && grails upgrade || grails set-grails-version GRAILS_VERSION
  && grails refresh-dependencies
  && grails test-app --non-interactive